/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedTestTestIdRouteImport } from './routes/_authenticated/test.$testId'
import { Route as AuthenticatedLearnTopicSlugRouteImport } from './routes/_authenticated/learn.$topicSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestTestIdRoute = AuthenticatedTestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnTopicSlugRoute =
  AuthenticatedLearnTopicSlugRouteImport.update({
    id: '/learn/$topicSlug',
    path: '/learn/$topicSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/learn/$topicSlug': typeof AuthenticatedLearnTopicSlugRoute
  '/test/$testId': typeof AuthenticatedTestTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/learn/$topicSlug': typeof AuthenticatedLearnTopicSlugRoute
  '/test/$testId': typeof AuthenticatedTestTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/_authenticated/learn/$topicSlug': typeof AuthenticatedLearnTopicSlugRoute
  '/_authenticated/test/$testId': typeof AuthenticatedTestTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/calendar'
    | '/dashboard'
    | '/teacher'
    | '/learn/$topicSlug'
    | '/test/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/calendar'
    | '/dashboard'
    | '/teacher'
    | '/learn/$topicSlug'
    | '/test/$testId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/teacher'
    | '/_authenticated/learn/$topicSlug'
    | '/_authenticated/test/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/test/$testId': {
      id: '/_authenticated/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof AuthenticatedTestTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$topicSlug': {
      id: '/_authenticated/learn/$topicSlug'
      path: '/learn/$topicSlug'
      fullPath: '/learn/$topicSlug'
      preLoaderRoute: typeof AuthenticatedLearnTopicSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
  AuthenticatedLearnTopicSlugRoute: typeof AuthenticatedLearnTopicSlugRoute
  AuthenticatedTestTestIdRoute: typeof AuthenticatedTestTestIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
  AuthenticatedLearnTopicSlugRoute: AuthenticatedLearnTopicSlugRoute,
  AuthenticatedTestTestIdRoute: AuthenticatedTestTestIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
